// DOM integration tests. These do not render a browser or measure visual layout.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const P=require('../core.js');
const html=fs.readFileSync('index.html','utf8');
const source=fs.readFileSync('app.js','utf8');
const styles=fs.readFileSync('styles.css','utf8');
const core=fs.readFileSync('core.js','utf8');
const K='magnus-training-planner:v1';
const settle=()=>new Promise(r=>setTimeout(r,25));
function boot({raw,url='https://example.test/planner/',noClipboard=false,noCompression=false,brokenStorage=false}={}){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=new JSDOM(html.replace('<link rel="stylesheet" href="styles.css">','<style>'+styles+'</style>'),{url,runScripts:'outside-only',virtualConsole:vc}),w=dom.window;
 let clipboard='',download=null,printed=false;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.TextEncoder=TextEncoder;w.Blob=Blob;w.Response=Response;
 if(!noCompression){w.CompressionStream=CompressionStream;w.DecompressionStream=DecompressionStream;}
 Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async s=>{if(noClipboard)throw Error('denied');clipboard=s;}}});
 w.URL.createObjectURL=b=>{download=b;return 'blob:https://example.test/test';};w.URL.revokeObjectURL=()=>{};
 w.HTMLAnchorElement.prototype.click=function(){};w.print=()=>{printed=true;};
 if(raw!==undefined)w.localStorage.setItem(K,raw);
 if(brokenStorage)Object.defineProperty(w,'localStorage',{value:{getItem(){throw Error('Unavailable');},setItem(){throw Error('Unavailable');}}});
 w.eval(core);w.eval(source);
 const $=id=>w.document.getElementById(id);
 const change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));};
 const click=id=>$(id).click();
 const input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('input',{bubbles:true}));};
 const choose=s=>change('week-picker',s);
 const saved=()=>JSON.parse(w.localStorage.getItem(K));
 const submit=(fields={})=>{const f=$('workout-form');for(const [k,v]of Object.entries(fields))f.elements.namedItem(k).value=v;f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));};
 return{dom,w,$,errors,change,click,input,choose,saved,submit,clipboard:()=>clipboard,download:()=>download,printed:()=>printed,close:()=>w.close()};
}
async function confirm(a,action,yes=true){a.click(action);await settle();assert.ok(a.$('confirm-dialog').open);a.click(yes?'confirm-yes':'confirm-no');await settle();}
function dragEvent(a,type,target,transfer){const e=new a.w.Event(type,{bubbles:true,cancelable:true});Object.defineProperty(e,'dataTransfer',{value:transfer});target.dispatchEvent(e);return e;}
test('initial index renders recovery week, totals, dates and fixed blocks',()=>{const a=boot();assert.equal(a.$('week-title').textContent,'Week 40');assert.equal(a.$('calendar').querySelectorAll('.day').length,7);assert.equal(a.$('calendar').querySelectorAll('.workout').length,5);assert.equal(a.$('calendar').querySelectorAll('.fixed-block').length,5);assert.ok(a.$('previous').disabled);assert.match(a.$('summary').textContent,/14km/);assert.match(a.$('coach-note').value,/Post-marathon/);assert.deepEqual(a.errors,[]);a.close();});
test('all 66 weeks navigate with correct dates, ISO years and boundary buttons',()=>{const a=boot();for(const s of P.weeks()){a.choose(s);assert.equal(a.$('week-title').textContent,'Week '+P.isoWeek(s).week);assert.equal(a.$('date-picker').value,s);assert.equal(a.$('week-picker').value,s);}assert.ok(a.$('next').disabled);a.change('date-picker','2027-01-01');assert.equal(a.$('week-title').textContent,'Week 53');assert.equal(a.$('week-picker').value,'2026-12-28');a.click('next');assert.equal(a.$('week-title').textContent,'Week 1');a.click('previous');assert.equal(a.$('week-title').textContent,'Week 53');a.click('current');assert.ok(P.inRange(a.$('week-picker').value));assert.deepEqual(a.errors,[]);a.close();});
test('transition week displays correct old/new commitments',()=>{const a=boot();a.choose('2026-10-12');const d=a.$('calendar').querySelectorAll('.day');assert.match(d[0].textContent,/08:00–18:00/);assert.match(d[1].textContent,/Work/);assert.match(d[2].textContent,/06:00–12:00/);assert.match(d[3].textContent,/09:00–16:00/);assert.doesNotMatch(d[3].textContent,/University/);a.close();});
test('add, edit all fields, move day, update totals, preserve independent weeks and reload',()=>{const a=boot();a.choose('2026-10-05');a.$('calendar').querySelector('[data-add="1"]').click();a.submit({type:'Run',name:'Coach test',day:'1',time:'07:15',duration:'40',distance:'7.5',intensity:'Steady',details:'4 × 5 min · ÆØÅ 🏃',comments:'Keep it controlled'});let s=a.saved(),x=s.weeks['2026-10-05'].workouts.find(x=>x.name==='Coach test');assert.equal(x.distance,7.5);assert.equal(x.day,1);assert.match(a.$('summary').textContent,/63.5km/);a.$('calendar').querySelector('[data-edit="'+x.id+'"]').click();a.submit({name:'Edited test',day:'2',time:'15:15',duration:'50',distance:'8',details:'New details',comments:'New coach comment'});x=a.saved().weeks['2026-10-05'].workouts.find(y=>y.id===x.id);assert.equal(x.name,'Edited test');assert.equal(x.time,'15:15');assert.equal(x.day,2);a.input('coach-note','Week-specific note');a.click('next');assert.doesNotMatch(a.$('calendar').textContent,/Edited test/);assert.notEqual(a.$('coach-note').value,'Week-specific note');a.click('previous');assert.equal(a.$('coach-note').value,'Week-specific note');const b=boot({raw:JSON.stringify(a.saved())});assert.match(b.$('calendar').textContent,/Edited test/);assert.equal(b.$('coach-note').value,'Week-specific note');assert.deepEqual(a.errors,[]);a.close();b.close();});
test('gym focus, optional distance and validation error',()=>{const a=boot();a.$('calendar').querySelector('[data-add="0"]').click();a.change('workout-type','Gym');assert.equal(a.$('focus-label').hidden,false);assert.equal(a.$('workout-intensity').value,'Strength');a.submit({name:'Upper test',focus:'Upper',duration:'50',distance:''});const w=a.saved().weeks[P.FIRST];assert.equal(P.summary(w).upper,2);assert.equal(w.workouts.at(-1).distance,null);a.$('calendar').querySelector('[data-add="0"]').click();a.submit({name:'Overnight',time:'23:30',duration:'120'});assert.match(a.$('editor-error').textContent,/midnight/);assert.ok(a.$('editor').open);a.close();});
test('delete requires confirmation and cancel preserves workout',async()=>{const a=boot();a.$('calendar').querySelector('.workout-button').click();await confirm(a,'delete-workout',false);assert.equal(a.$('calendar').querySelectorAll('.workout').length,5);await confirm(a,'delete-workout');assert.equal(a.$('calendar').querySelectorAll('.workout').length,4);assert.ok(!a.$('editor').open);a.close();});
test('drag/drop changes day, preserves time, highlights target and leaves fixed blocks',()=>{const a=boot();a.choose('2026-10-05');const doc=a.w.document,handle=doc.querySelector('.day[data-day="2"] .drag-handle'),id=handle.dataset.id,target=doc.querySelector('.day[data-day="1"]');let transfer={setData(){},setDragImage(){}};dragEvent(a,'dragstart',handle,transfer);dragEvent(a,'dragover',target,transfer);assert.ok(target.classList.contains('drag-over'));dragEvent(a,'drop',target,transfer);const x=a.saved().weeks['2026-10-05'].workouts.find(x=>x.id===id);assert.equal(x.day,1);assert.equal(x.time,'13:00');assert.equal(doc.querySelectorAll('.fixed-block[draggable]').length,0);assert.equal(doc.querySelectorAll('.drag-over').length,0);assert.match(doc.querySelector('.day[data-day="1"]').textContent,/Schedule overlap/);const times=Array.from(doc.querySelectorAll('.day[data-day="1"] .card-top')).map(x=>x.textContent.match(/\d\d:\d\d/)[0]);assert.deepEqual(times,['13:00','17:30']);a.close();});
test('copy previous copies current edits, notes and independent IDs',async()=>{const a=boot();a.input('coach-note','Recovery amended');a.click('next');await confirm(a,'copy-previous');assert.equal(a.$('coach-note').value,'Recovery amended');assert.equal(a.$('calendar').querySelectorAll('.workout').length,5);a.input('coach-note','Next week');a.click('previous');assert.equal(a.$('coach-note').value,'Recovery amended');a.close();});
test('copy next confirms overwrite and reset/clear are scoped to one week',async()=>{const a=boot();a.choose('2026-10-05');a.input('coach-note','Keep this note');a.click('copy-next');await settle();assert.equal(a.saved().weeks['2026-10-12'].note,'Keep this note');a.input('coach-note','Updated note');await confirm(a,'copy-next',false);assert.equal(a.saved().weeks['2026-10-12'].note,'Keep this note');await confirm(a,'copy-next');assert.equal(a.saved().weeks['2026-10-12'].note,'Updated note');await confirm(a,'clear-week');assert.equal(a.$('calendar').querySelectorAll('.workout').length,0);assert.equal(a.$('calendar').querySelectorAll('.fixed-block').length,5);assert.equal(a.$('coach-note').value,'Updated note');assert.equal(a.saved().weeks['2026-10-12'].workouts.length,11);await confirm(a,'reset-week');assert.equal(a.$('week-badge').textContent,'Default week');assert.equal(a.$('calendar').querySelectorAll('.workout').length,11);assert.equal(a.saved().weeks['2026-10-12'].note,'Updated note');a.close();});
test('week link roundtrip preserves Unicode, isolates local data and can save shared edits',async()=>{const a=boot();a.choose('2026-10-05');a.input('coach-note','Threshold ÆØÅ 🏃');a.click('share-week');await settle();const url=a.clipboard();assert.match(url,/#plan=g/);assert.ok(url.length<8000);const local=P.empty();local.weeks[P.FIRST]=P.defaultWeek(P.FIRST);local.weeks[P.FIRST].note='Local note';const b=boot({url,raw:JSON.stringify(local)});await settle();assert.equal(b.$('coach-note').value,'Threshold ÆØÅ 🏃');assert.equal(b.$('shared-banner').hidden,false);assert.equal(b.saved().weeks[P.FIRST].note,'Local note');assert.equal(b.saved().weeks['2026-10-05'],undefined);b.input('coach-note','Coach changed this');await confirm(b,'save-shared');assert.equal(b.saved().weeks['2026-10-05'].note,'Coach changed this');assert.equal(b.saved().weeks[P.FIRST].note,'Local note');assert.equal(b.$('shared-banner').hidden,true);assert.equal(b.w.location.hash,'');assert.deepEqual(b.errors,[]);a.close();b.close();});
test('shared plan return discards draft without changing saved plan',async()=>{const a=boot();a.click('share-week');await settle();const local=P.empty('2026-10-12');local.weeks['2026-10-12']=P.defaultWeek('2026-10-12');local.weeks['2026-10-12'].note='My local';const b=boot({url:a.clipboard(),raw:JSON.stringify(local)});await settle();b.input('coach-note','Temporary draft');await confirm(b,'leave-shared');assert.equal(b.$('coach-note').value,'My local');assert.equal(b.saved().selected,'2026-10-12');a.close();b.close();});
test('full plan link includes independent weeks and defaults',async()=>{const a=boot();a.input('coach-note','A');a.choose('2027-12-27');a.input('coach-note','Z');a.click('share-full');await settle();const b=boot({url:a.clipboard()});await settle();assert.equal(b.$('coach-note').value,'Z');b.choose(P.FIRST);assert.equal(b.$('coach-note').value,'A');b.choose('2027-01-04');assert.equal(b.$('calendar').querySelectorAll('.workout').length,11);a.close();b.close();});
test('clipboard failure exposes manual copy; uncompressed links also open',async()=>{const a=boot({noClipboard:true,noCompression:true});a.click('share-week');await settle();assert.equal(a.$('link-fallback').hidden,false);assert.match(a.$('share-message').textContent,/Select and copy/);assert.match(a.$('link-text').value,/#plan=j/);const b=boot({url:a.$('link-text').value});await settle();assert.equal(b.$('shared-banner').hidden,false);assert.equal(b.$('calendar').querySelectorAll('.workout').length,5);a.close();b.close();});
test('oversized links recommend JSON; malformed links preserve local weeks',async()=>{const a=boot({noCompression:true});a.input('coach-note','a'.repeat(20000));a.click('share-full');await settle();assert.match(a.$('share-message').textContent,/too large/);const raw=JSON.stringify(a.saved());const b=boot({raw,url:'https://example.test/planner/#plan=gDefinitelyNotGzip'});await settle();assert.match(b.$('storage-warning').textContent,/could not be opened/);assert.equal(b.saved().weeks[P.FIRST].note,'a'.repeat(20000));a.close();b.close();});
test('JSON export/import preserves data, confirms overwrite, retains unrelated weeks',async()=>{const a=boot();a.input('coach-note','Exported note');a.click('export');const json=await a.download().text();assert.equal(JSON.parse(json).weeks[P.FIRST].note,'Exported note');const b=boot();b.choose('2026-10-05');b.input('coach-note','Unrelated note');const input=b.$('import-file');Object.defineProperty(input,'files',{configurable:true,value:[{size:json.length,text:async()=>json}]});input.dispatchEvent(new b.w.Event('change'));await settle();assert.ok(b.$('confirm-dialog').open);b.click('confirm-yes');await settle();assert.equal(b.$('coach-note').value,'Exported note');assert.equal(b.saved().weeks['2026-10-05'].note,'Unrelated note');a.close();b.close();});
test('invalid JSON import leaves existing data untouched',async()=>{const a=boot();a.input('coach-note','Keep me');const input=a.$('import-file');Object.defineProperty(input,'files',{value:[{size:5,text:async()=>'{nope'}]});input.dispatchEvent(new a.w.Event('change'));await settle();assert.match(a.$('share-message').textContent,/Import failed/);assert.equal(a.saved().weeks[P.FIRST].note,'Keep me');a.close();});
test('injected HTML stays text; print includes details and coach note',()=>{const a=boot();a.$('calendar').querySelector('[data-add="0"]').click();a.submit({name:'<img src=x onerror=alert(1)>',details:'<script>alert(1)</script>',comments:'Coach <b>text</b>'});assert.equal(a.$('calendar').querySelectorAll('img,script').length,0);assert.match(a.$('calendar').textContent,/<img/);a.input('coach-note','Printed coaching note');assert.equal(a.$('print-note').textContent,'Printed coaching note');assert.match(a.w.document.querySelector('.print-details').textContent,/<script>/);a.click('print');assert.ok(a.printed());a.close();});
test('corrupt/blocked storage is not overwritten and runtime remains usable',()=>{const a=boot({raw:'corrupt'});assert.equal(a.w.localStorage.getItem(K),'corrupt');assert.equal(a.$('storage-warning').hidden,false);assert.equal(a.$('calendar').querySelectorAll('.day').length,7);assert.deepEqual(a.errors,[]);const b=boot({brokenStorage:true});assert.match(b.$('save-status').textContent,/Not saved/);assert.deepEqual(b.errors,[]);a.close();b.close();});
test('mobile day editor alternative, print CSS and responsive breakpoints are present',()=>{const a=boot();a.$('calendar').querySelector('.workout-button').click();assert.equal(a.$('workout-day').options.length,7);a.submit({day:'0'});assert.equal(a.$('calendar').querySelector('.day[data-day="0"] .workout').querySelector('h4').textContent,'Very easy bike');const css=fs.readFileSync('styles.css','utf8');assert.match(css,/@media\(max-width:480px\)/);assert.match(css,/@media\(max-width:800px\)/);assert.match(css,/@media print/);assert.match(css,/@page\{size:A4 landscape/);a.close();});
